### ISSUE TITLE
reCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by DrakoPOD** [bbonch/vue3-recaptcha2#5] opened 2021-05-28 23:24 UTC
I just follow the example:
```vue
<template>
  <vue-recaptcha
          siteKey="..."
          :show="show"
          size="normal"
          theme="dark"
          @verify="recaptchaVerified"
          @expire="recaptchaExpired"
          @fail="recaptchaFailed"
          ref="recaptcha">
  </vue-recaptcha>
</template>

<script>
import { defineComponent, ref } from 'vue';
import vueRecaptcha from 'vue3-recaptcha2';

export default defineComponent({
  components: {
     vueRecaptcha
  },
  setup(){
    const recaptcha = ref('')

    return{
      recaptcha,

      show: ref(false),
      recaptchaVerified(response) {},
      recaptchaExpired() {
        recaptcha.value.reset();
      },
      recaptchaFailed() {}
    }
  }
})
</script>
```

**Comment by bbonch** [comment] 2021-05-29 11:52
Duplicate of #2

**Closed** 2021-05-29 11:52 UTC

**Comment by bbonch** [comment] 2021-05-29 12:08
@DrakoPOD Try now. Show option was removed.
